# Generated by Django 4.1 on 2022-09-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('USERPAGE', 'Userpage'), ('SUPERVISORPSM', 'Supervisorpsm'), ('BOSSADMIN', 'Bossadmin')], default='USERPAGE', max_length=256, verbose_name='Type')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_names', models.CharField(blank=True, max_length=150, verbose_name='First names')),
                ('last_names', models.CharField(blank=True, max_length=150, verbose_name='Last names')),
                ('birth_date', models.DateField(blank=True, max_length=150, verbose_name='Date of birth')),
                ('type_identification', models.CharField(blank=True, max_length=150, verbose_name='Type of identification')),
                ('identification_num', models.BigIntegerField(blank=True, unique=True, verbose_name='Identification Number')),
                ('password', models.CharField(max_length=150, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_identification', models.CharField(max_length=150, verbose_name='Type of identification')),
                ('identification_num', models.BigIntegerField(unique=True, verbose_name='Identification Number')),
                ('lastChangeDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True, verbose_name='Is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisorpsm',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acomApp.user',),
        ),
        migrations.CreateModel(
            name='Userpage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acomApp.user',),
        ),
    ]
