# Generated by Django 4.1 on 2022-09-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acomApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='identification_num',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type_identification',
        ),
    ]
