# Generated by Django 4.1 on 2022-09-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomApp', '0002_remove_account_identification_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='is Active'),
        ),
        migrations.AddField(
            model_name='user',
            name='testResult',
            field=models.BooleanField(default=True, verbose_name='test Result'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
